### ISSUE TITLE
Compile `ncspot` with the `cover` feature.

### ISSUE THREAD

**Issue by Hooregi** [hapakaien/aur-packages#11]
I think `ueberzug` is a pretty common dependency, I know I certainly use it for `ytfzf` and images in vim. So, I was wondering if it was possible to compile the binary with the 'cover' feature.

Also, the AUR package is currently out-of-date.

If there's anything I can do to help please let me know!

**Comment by hapakaien** [comment]
`ueberzug` has X11 as one of its dependencies. I haven't tried compiling it yet. But, since I'm using Wayland, I thought this would be a problem. I hope I'm wrong on this.

Sorry for late reply. I forgot to watch this repo.

**Comment by Hooregi** [comment]
No you're right, the only way for `ueberzug` to work on `wayland` would be through an `xwayland` client, so the solution would be terminal dependent. And the lead for `ueberzug` already said he won't implement wayland support. Thanks for answering though, nice job keeping the package up to date.

**Comment by joaopauloalbq** [comment]
Could you compile with _cover_ flag and add _ueberzug_ as an optional dependency? 
Covers in notifications only appear with the flag enabled now :(

![cover](https://user-images.githubusercontent.com/9905202/166187684-cbc5d9cd-a9a0-47c0-9047-93e6497409c9.png)

**Comment by hapakaien** [comment]
Since my implementation in CI requires a build of ncspot before building the AUR package, I can only do that in the next release of ncspot. Is that okay @joaopauloalbq?

**Comment by joaopauloalbq** [comment]
It's totally fine, thank you :)

**Comment by hapakaien** [comment]
How about this https://github.com/hapakaien/aur-packages/pull/18 PR, @joaopauloalbq? Is there anything else I need to do?

**Comment by joaopauloalbq** [comment]
That's it, looks great!
